# X Ray Case Study in Python
**Author: Mahadevan Balasubramaniam, MBB

The objective of the exercise is to use Jupyter Notebook for the XRay casestudy. This is an hands-on exercise for students

**Define the Imports for the Program
The program uses the uncertainties module to perform the rollup


In [1]:
# Import the Modules into the Notebook
from uncertainties import ufloat
from uncertainties import wrap
from uncertainties.umath import * 
import numpy as np
import pandas as pd

# Define the overall CTQ Flowdown structure
# 1. fsAlign

## 1.1 Detector

## 1.2 Source
### 1.2.1 Tube
### 1.2.2 Beam
#### 1.2.2.1 Material
#### 1.2.2.2 Geometry

Though the structure looks hierarchical - all the variables are essentially in a flattened structure

The ufloat objects are stored in an nested dictionary structure to permit easy access/reset and use throughout the program

In [46]:
# Setup the Structure

# Geometry
geometryDict = {}
geometryDict['beamHeight'] = ufloat(100, 0.25, 'h')
geometryDict['beamLength'] = ufloat(500, 0.2, 'L')
geometryDict['beamThick'] = ufloat(4.5, 0.1, 't')
geometryDict['beamWidth'] = ufloat(50, 0.25, 'w')
print geometryDict

materialDict = {}
materialDict['elasticModulus'] = ufloat(200E9, 6.67E9, 'E')
materialDict['density'] = ufloat(8.8E-6, 0, 'rho')
print materialDict

tubeDict = {}
tubeDict['tubePos'] = ufloat(0, 0.0333, 'tubePos')
tubeDict['tubeMass'] = ufloat(90, 0.08333, 'tubeMass')
tubeDict['gravity'] = ufloat(9.81, 0, 'g')
print tubeDict

beamDict = {}
beamDict['beamDeflection'] = ufloat(0, 0, 'beamDefl')
beamDict['beamFrequency'] = ufloat(0, 0, 'beamFreq')
beamDict['beamStress'] = ufloat(0, 0, 'beamStress')
beamDict['beamMass'] = ufloat(0, 0, 'beamMass')
print beamDict

sourceDict = {}
sourceDict['pos'] = ufloat(0, 0, 'sourcePos')
sourceDict['beamDistToCL'] = ufloat(600, 0.0667, 'sourceR')
sourceDict['omega'] = ufloat(12.56, 0.041867, 'omega')
sourceDict['force'] = ufloat(0, 0, 'F')
print sourceDict

detectorDict = {}
detectorDict['pos'] = ufloat(-0.5, 0.0333, 'detectorPos')
print detectorDict

xRayDict = {}
xRayDict['fsAlign'] = ufloat(0, 0, 'fsAlign')
print xRayDict

{'beamHeight': < h = 100.0+/-0.25 >, 'beamWidth': < w = 50.0+/-0.25 >, 'beamThick': < t = 4.5+/-0.1 >, 'beamLength': < L = 500.0+/-0.2 >}
{'elasticModulus': < E = 200000000000.0+/-6670000000.0 >, 'density': < rho = 8.8e-06+/-0 >}
{'gravity': < g = 9.81+/-0 >, 'tubeMass': < tubeMass = 90.0+/-0.08333 >, 'tubePos': < tubePos = 0.0+/-0.0333 >}
{'beamFrequency': < beamFreq = 0.0+/-0 >, 'beamMass': < beamMass = 0.0+/-0 >, 'beamDeflection': < beamDefl = 0.0+/-0 >, 'beamStress': < beamStress = 0.0+/-0 >}
{'force': < F = 0.0+/-0 >, 'beamDistToCL': < sourceR = 600.0+/-0.0667 >, 'omega': < omega = 12.56+/-0.041867 >, 'pos': < sourcePos = 0.0+/-0 >}
{'pos': < detectorPos = -0.5+/-0.0333 >}
{'fsAlign': < fsAlign = 0.0+/-0 >}


In [47]:
# To permit calling and transferring information across all subsystems
# Package it into an overall dict so that the
# Analytical and Response Surface can be programmed inside the functional blocks
overallSystemDict = {}
overallSystemDict['xRayDict'] = xRayDict
overallSystemDict['detectorDict'] = detectorDict
overallSystemDict['sourceDict'] = sourceDict
overallSystemDict['beamDict'] = beamDict
overallSystemDict['tubeDict'] = tubeDict
overallSystemDict['materialDict'] = materialDict
overallSystemDict['geometryDict'] = geometryDict
print overallSystemDict


{'detectorDict': {'pos': < detectorPos = -0.5+/-0.0333 >}, 'materialDict': {'elasticModulus': < E = 200000000000.0+/-6670000000.0 >, 'density': < rho = 8.8e-06+/-0 >}, 'sourceDict': {'force': < F = 0.0+/-0 >, 'beamDistToCL': < sourceR = 600.0+/-0.0667 >, 'omega': < omega = 12.56+/-0.041867 >, 'pos': < sourcePos = 0.0+/-0 >}, 'geometryDict': {'beamHeight': < h = 100.0+/-0.25 >, 'beamWidth': < w = 50.0+/-0.25 >, 'beamThick': < t = 4.5+/-0.1 >, 'beamLength': < L = 500.0+/-0.2 >}, 'tubeDict': {'gravity': < g = 9.81+/-0 >, 'tubeMass': < tubeMass = 90.0+/-0.08333 >, 'tubePos': < tubePos = 0.0+/-0.0333 >}, 'xRayDict': {'fsAlign': < fsAlign = 0.0+/-0 >}, 'beamDict': {'beamFrequency': < beamFreq = 0.0+/-0 >, 'beamMass': < beamMass = 0.0+/-0 >, 'beamDeflection': < beamDefl = 0.0+/-0 >, 'beamStress': < beamStress = 0.0+/-0 >}}


# Analytical and Response Surface Transfer Functions

The response surface transfer functions have been exported to pickle files in the XRay Response Surface notebook

The analytical transfer functions need to be typed in by the students.

Technically, all the formulas can be put into one large code and updated in one go. But here we take an easy way out by mutually separating out the analytical and response surface functions into three steps
## Analytical_Lower
### Calculate Beam Mass
### Calculate Force

## Reponse Surface
### Utilize the Geometry Parameters & Force to calculate Stress, Frequency and Deflection
The response surface calculation is done in a coded space

## Analytical_Upper
### Use Deflection and calculate the fsAlign


In [48]:
# Define Analytical Equations
def defineAnalyticalEquations_Lower(overallSystemDict):
    # Equation 1
    L = overallSystemDict['geometryDict']['beamLength']
    w = overallSystemDict['geometryDict']['beamWidth']
    t = overallSystemDict['geometryDict']['beamThick']
    h = overallSystemDict['geometryDict']['beamHeight']
    density = overallSystemDict['materialDict']['density']
    # User Enters Formula
    beamMass = density * L * (2 * (w + 2 * t)*t + 2 * h * t)
    
    # Equation 2
    tubeMass = overallSystemDict['tubeDict']['tubeMass']
    beamDistToCL = overallSystemDict['sourceDict']['beamDistToCL']
    gravity = overallSystemDict['tubeDict']['gravity']
    omega =  overallSystemDict['sourceDict']['omega']
    # User Enters Formula
    force = tubeMass * (0.001 * beamDistToCL * omega * omega + gravity)
    

    # Pushed back into the Dict
    overallSystemDict['beamDict']['beamMass'] = beamMass
    overallSystemDict['sourceDict']['force'] = force
    
    return overallSystemDict

In [49]:
# 'h', 'w', 't', 'L', 'E', 'F', 
# 'h^2', 'h w', 'h t', 'h L', 'h E', 'h F', 
# 'w^2', 'w t', 'w L', 'w E', 'w F', 
# 't^2', 't L', 't E', 't F', 
# 'L^2', 'L E', 'L F', 
# 'E^2', 'E F', 
# 'F^2'
def calculateResponseValue(h, w, t, L, E, F, coef, intercept):
    term1 = h*coef[0] + w*coef[1] + t*coef[2] + L*coef[3] + E*coef[4] + F*coef[5]
    term2 = h * (h*coef[6] + w*coef[7] + t*coef[8] + L*coef[9] + E*coef[10] + F*coef[11])
    term3 = w * (w*coef[12] + t*coef[13] + L*coef[14] + E*coef[15] + F*coef[16])

    term4 = t * (t*coef[17] + L*coef[18] + E*coef[19] + F*coef[20])
    term5 = L * (L*coef[21] + E*coef[22] + F*coef[23])
    term6 = E * (E*coef[24] + F*coef[25])
    term7 = F * F * coef[26]
    return intercept + term1 + term2 + term3 + term4 + term5 + term6 + term7
    

In [50]:
def calculateCodedValues(h, w, t, L, E, F):
    # 6 Variables: h, w, t, L, E, F
    lb = np.array([80, 40, 2, 400, 180E9, 9000])
    ub = np.array([120, 60, 7, 600, 220E9, 11000])
    avg = 0.5 * (lb + ub)

    loc_array = np.array([h, w, t, L, E, F])
    loc_array_coded = (loc_array - avg) / (ub - lb) * 2.0
    #print loc_array, loc_array_coded
    return list(loc_array_coded)
    
# Define Response Surface Equations
def defineResponseSurface(overallSystemDict, freq_rs, deflection_rs, stress_rs):
    L = overallSystemDict['geometryDict']['beamLength']
    w = overallSystemDict['geometryDict']['beamWidth']
    t = overallSystemDict['geometryDict']['beamThick']
    h = overallSystemDict['geometryDict']['beamHeight']
    E = overallSystemDict['materialDict']['elasticModulus']
    F = overallSystemDict['sourceDict']['force']
    
    h_c, w_c, t_c, L_c, E_c, F_c = calculateCodedValues(h, w, t, L, E, F)
    
    
    #x_vars = np.array([h, w, t, L, E, F])
    #x_vars_n = np.array([h.n, w.n, t.n, L.n, E.n, F.n])
    #x_vars_2d = x_vars.reshape(-1,1).transpose()
    #print x_vars_2d.shape
    # beamDeflection
    beamDeflection = calculateResponseValue(h, w, t, L, E, F, deflection_rs.steps[1][1].coef_[0,1:], deflection_rs.steps[1][1].intercept_[0])
    #beamDeflection = wrap(deflection_rs.predict)(x_vars_2d)
    #loc_I = (w * h * h * h/12)
    #beamDeflection = (1.0/(E * loc_I)) * F * L * L * L
    
    # beamFrequency
    beamFrequency = calculateResponseValue(h, w, t, L, E, F, freq_rs.steps[1][1].coef_[0,1:], freq_rs.steps[1][1].intercept_[0])
    #beamFrequency = wrap(freq_rs.predict)(x_vars_2d)
    #beamFrequency = E * w * h * h * h/12
    
    # beamStress
    beamStress = calculateResponseValue(h, w, t, L, E, F, stress_rs.steps[1][1].coef_[0,1:], stress_rs.steps[1][1].intercept_[0])
    #beamStress = wrap(stress_rs.predict)(x_vars_2d)
    #beamStress = F/(w * t)
    
    
    beamDict['beamDeflection'] = beamDeflection
    beamDict['beamFrequency'] = beamFrequency
    beamDict['beamStress'] = beamStress
    return overallSystemDict

In [51]:
# Define Analytical Equations
# Has some dependency on the Response Surface Equations.. So split it into two parts (Lower and Upper)
def defineAnalyticalEquations_Upper(overallSystemDict):
    # Equation 3
    tubePos = overallSystemDict['tubeDict']['tubePos']
    beamDeflection = overallSystemDict['beamDict']['beamDeflection']
    # User Enters Formula
    sourcePos = tubePos - beamDeflection
    
    # Equation 4
    detectorPos = overallSystemDict['detectorDict']['pos']
    # User Enters Formula
    fsAlign = detectorPos - sourcePos
    
    # Pushed back into the Dict
    overallSystemDict['sourceDict']['pos'] = sourcePos
    overallSystemDict['fsAlign'] = fsAlign
    return overallSystemDict
    

In [52]:
# Test out a simple calculation
from sklearn.externals import joblib

# Load the response surfaces
# https://stackoverflow.com/questions/34373606/scikit-learn-coefficients-polynomialfeatures
freq_rs = joblib.load('freq_rs.pkl')
print freq_rs.steps[1][1].coef_.shape
print freq_rs.steps[1][1].intercept_

deflection_rs = joblib.load('deflection_rs.pkl')
stress_rs = joblib.load('stress_rs.pkl')

overallSystemDict = defineAnalyticalEquations_Lower(overallSystemDict)
overallSystemDict = defineResponseSurface(overallSystemDict, freq_rs, deflection_rs, stress_rs)
overallSystemDict = defineAnalyticalEquations_Upper(overallSystemDict)
print overallSystemDict

(1, 28)
[27.50748961]
{'detectorDict': {'pos': < detectorPos = -0.5+/-0.0333 >}, 'materialDict': {'elasticModulus': < E = 200000000000.0+/-6670000000.0 >, 'density': < rho = 8.8e-06+/-0 >}, 'sourceDict': {'force': 9401.5944+/-57.46280148823399, 'beamDistToCL': < sourceR = 600.0+/-0.0667 >, 'omega': < omega = 12.56+/-0.041867 >, 'pos': -0.8701628007248919+/-0.04301007499362918}, 'geometryDict': {'beamHeight': < h = 100.0+/-0.25 >, 'beamWidth': < w = 50.0+/-0.25 >, 'beamThick': < t = 4.5+/-0.1 >, 'beamLength': < L = 500.0+/-0.2 >}, 'tubeDict': {'gravity': < g = 9.81+/-0 >, 'tubeMass': < tubeMass = 90.0+/-0.08333 >, 'tubePos': < tubePos = 0.0+/-0.0333 >}, 'fsAlign': 0.37016280072489194+/-0.05439445331058679, 'xRayDict': {'fsAlign': < fsAlign = 0.0+/-0 >}, 'beamDict': {'beamFrequency': 54.71261517436952+/-0.9967051363964022, 'beamMass': 6.2964+/-0.14852282230173783, 'beamDeflection': 0.8701628007248919+/-0.02722088446317654, 'beamStress': 112.07475227086393+/-2.0564129698467237}}


In [53]:
import scipy.stats as st

# Define DPMO and perform the optimization on variables
# Calculate the dpmo given the ufloat object and the lsl & usl
def dpo_lsl_usl(in_ufloat, lsl, usl):
    loc_mean = in_ufloat.nominal_value
    loc_std = in_ufloat.std_dev
    ret_dpo = 0.0

    if(~np.isnan(lsl)):
        z_lsl = (loc_mean - lsl) * 1.0/loc_std
        loc_lslcdf = st.norm.cdf(z_lsl)
        ret_dpo += 1 - loc_lslcdf
    
    if(~np.isnan(usl)):
        z_usl = (usl - loc_mean) * 1.0/loc_std
        loc_uslcdf = st.norm.cdf(z_usl)
        ret_dpo += 1.0 - loc_uslcdf
    
    # Find the Zoverall for the ret_dpo
    ret_zoverall = st.norm.ppf(1 - ret_dpo)

    return ret_dpo, ret_zoverall

In [54]:
import scipy.optimize as optimize

# params h, w, L, t
# Forward calculate to return an overallSystemDict object
def forwardCalculate(params, overallSystemDict=overallSystemDict):
    print(params)  # <-- you'll see that params is a NumPy array
    h_nom, w_nom, t_nom, L_nom = params # <-- for readability you may wish to assign names to the component variables
    # Set the values into the Overall System Dict
    L_std = (overallSystemDict['geometryDict']['beamLength']).std_dev
    w_std = (overallSystemDict['geometryDict']['beamWidth']).std_dev
    t_std = (overallSystemDict['geometryDict']['beamThick']).std_dev
    h_std = (overallSystemDict['geometryDict']['beamHeight']).std_dev
    
    overallSystemDict['geometryDict']['beamLength'] = ufloat(L_nom, L_std, 'L') 
    overallSystemDict['geometryDict']['beamWidth'] = ufloat(w_nom, w_std, 'w')
    overallSystemDict['geometryDict']['beamThick'] = ufloat(t_nom, t_std, 't')
    overallSystemDict['geometryDict']['beamHeight'] = ufloat(h_nom, h_std, 'h')
    
    
    overallSystemDict = defineAnalyticalEquations_Lower(overallSystemDict)
    overallSystemDict = defineResponseSurface(overallSystemDict, freq_rs, deflection_rs, stress_rs)
    overallSystemDict = defineAnalyticalEquations_Upper(overallSystemDict)
    return overallSystemDict

def calculateDPMO(overallSystemDict):
    beamFrequency = overallSystemDict['beamDict']['beamFrequency']
    beamStress = overallSystemDict['beamDict']['beamStress']
    beamMass = overallSystemDict['beamDict']['beamMass']
    fsAlign = overallSystemDict['fsAlign']
    
    # print beamFrequency, beamStress, beamMass, fsAlign
    
    dpo_beamFrequency, z_beamFrequency = dpo_lsl_usl(beamFrequency, np.nan, 55.0)
    #bounds_beamFrequency = (np.nan, 55)
    dpo_beamStress, z_beamStress = dpo_lsl_usl(beamStress, np.nan, 120)
    #bounds_beamStress = (np.nan, 20)
    dpo_beamMass, z_beamMass = dpo_lsl_usl(beamMass, np.nan, 8.0)
    #bounds_beamMass = (np.nan, 8)
    dpo_fsAlign, z_fsAlign = dpo_lsl_usl(fsAlign, -0.8, 0.8)
    #bounds_fsAlign = (0.4, 0.6)
    dpo_avg = 0.25 * (dpo_beamFrequency + dpo_beamStress + dpo_beamMass + dpo_fsAlign)

    print 'Frequency: %f +/- %f dpmo: %f, z: %f'%(beamFrequency.nominal_value, beamFrequency.std_dev, dpo_beamFrequency, z_beamFrequency)
    print 'Stress: %f +/- %f dpmo: %f, z: %f'%(beamStress.nominal_value, beamStress.std_dev, dpo_beamStress, z_beamStress)
    print 'fsAlign: %f +/- %f dpmo: %f, z: %f'%(fsAlign.nominal_value, fsAlign.std_dev, dpo_fsAlign, z_fsAlign)
    print 'Mass: %f +/- %f dpmo: %f, z: %f'%(beamMass.nominal_value, beamMass.std_dev, dpo_beamMass, z_beamMass)
    
    
    return dpo_avg
    
# params: h, w, L, t
def f(params, overallSystemDict=overallSystemDict):
    overallSystemDict = forwardCalculate(params, overallSystemDict)
    # Calculate the DPO of each variable
    dpo_avg = calculateDPMO(overallSystemDict)
    return dpo_avg

h_Nom_init = 100 #(overallSystemDict['geometryDict']['beamHeight']).nominal_value
w_Nom_init = 50 #(overallSystemDict['geometryDict']['beamWidth']).nominal_value
t_Nom_init = 4.5 #(overallSystemDict['geometryDict']['beamThick']).nominal_value
L_Nom_init = 500 #(overallSystemDict['geometryDict']['beamLength']).nominal_value

initial_guess = [h_Nom_init, w_Nom_init, t_Nom_init, L_Nom_init]
bounds = np.c_[[80, 40, 2, 400], [120, 60, 7, 600]]
result = optimize.minimize(f, initial_guess, method='BFGS', bounds=bounds, options={'gtol': 1e-6, 'disp': True})
if result.success:
    fitted_params = result.x
    print(fitted_params)
    overallSystemDict = forwardCalculate(fitted_params, overallSystemDict)
else:
    raise ValueError(result.message)

[100.   50.    4.5 500. ]
Frequency: 54.712615 +/- 0.996705 dpmo: 0.386545, z: 0.288335
Stress: 112.074752 +/- 2.056413 dpmo: 0.000058, z: 3.853918
fsAlign: 0.370163 +/- 0.054394 dpmo: 0.000000, z: 7.905690
Mass: 6.296400 +/- 0.148523 dpmo: 0.000000, z: inf
[100.00000001  50.           4.5        500.        ]
Frequency: 54.712615 +/- 0.996705 dpmo: 0.386545, z: 0.288335
Stress: 112.074752 +/- 2.056413 dpmo: 0.000058, z: 3.853918
fsAlign: 0.370163 +/- 0.054394 dpmo: 0.000000, z: 7.905690
Mass: 6.296400 +/- 0.148523 dpmo: 0.000000, z: inf
[100.          50.00000001   4.5        500.        ]
Frequency: 54.712615 +/- 0.996705 dpmo: 0.386545, z: 0.288335
Stress: 112.074752 +/- 2.056413 dpmo: 0.000058, z: 3.853918
fsAlign: 0.370163 +/- 0.054394 dpmo: 0.000000, z: 7.905690
Mass: 6.296400 +/- 0.148523 dpmo: 0.000000, z: inf
[100.          50.           4.50000001 500.        ]
Frequency: 54.712615 +/- 0.996705 dpmo: 0.386545, z: 0.288335
Stress: 112.074752 +/- 2.056413 dpmo: 0.000058, z: 3.8

Frequency: 53.093217 +/- 0.955746 dpmo: 0.023017, z: 1.995074
Stress: 116.153477 +/- 2.128513 dpmo: 0.035370, z: 1.807141
fsAlign: 0.407985 +/- 0.053887 dpmo: 0.000000, z: 7.274839
Mass: 5.966259 +/- 0.147392 dpmo: 0.000000, z: inf
[ 99.5431447   50.0297486    4.28540424 500.2023575 ]
Frequency: 53.093217 +/- 0.955746 dpmo: 0.023017, z: 1.995074
Stress: 116.153477 +/- 2.128513 dpmo: 0.035370, z: 1.807141
fsAlign: 0.407985 +/- 0.053887 dpmo: 0.000000, z: 7.274839
Mass: 5.966259 +/- 0.147392 dpmo: 0.000000, z: inf
[ 99.5431447   50.02974859   4.28540425 500.2023575 ]
Frequency: 53.093217 +/- 0.955746 dpmo: 0.023017, z: 1.995074
Stress: 116.153476 +/- 2.128513 dpmo: 0.035370, z: 1.807141
fsAlign: 0.407985 +/- 0.053887 dpmo: 0.000000, z: 7.274839
Mass: 5.966259 +/- 0.147392 dpmo: 0.000000, z: inf
[ 99.5431447   50.02974859   4.28540424 500.20235752]
Frequency: 53.093217 +/- 0.955746 dpmo: 0.023017, z: 1.995074
Stress: 116.153477 +/- 2.128513 dpmo: 0.035370, z: 1.807141
fsAlign: 0.407985 +/

Frequency: 49.367305 +/- 0.866950 dpmo: 0.000000, z: 6.497141
Stress: 112.458504 +/- 2.062922 dpmo: 0.000128, z: 3.655735
fsAlign: 0.486846 +/- 0.052909 dpmo: 0.000000, z: 5.918764
Mass: 7.235248 +/- 0.140710 dpmo: 0.000000, z: 5.434936
[ 81.99360485  51.72918139   5.58352299 508.15303924]
Frequency: 49.367305 +/- 0.866950 dpmo: 0.000000, z: 6.497141
Stress: 112.458504 +/- 2.062922 dpmo: 0.000128, z: 3.655735
fsAlign: 0.486846 +/- 0.052909 dpmo: 0.000000, z: 5.918764
Mass: 7.235248 +/- 0.140710 dpmo: 0.000000, z: 5.434936
[ 80.40273074  51.88337597   5.70360077 508.87381695]
Frequency: 49.044275 +/- 0.859666 dpmo: 0.000000, z: 6.927954
Stress: 112.083169 +/- 2.056555 dpmo: 0.000059, z: 3.849559
fsAlign: 0.493649 +/- 0.052830 dpmo: 0.000000, z: 5.798853
Mass: 7.340209 +/- 0.140110 dpmo: 0.000001, z: 4.709104
[ 80.40273074  51.88337597   5.70360077 508.87381695]
Frequency: 49.044275 +/- 0.859666 dpmo: 0.000000, z: 6.927954
Stress: 112.083169 +/- 2.056555 dpmo: 0.000059, z: 3.849559
fsAli

Frequency: 48.905550 +/- 0.856560 dpmo: 0.000000, z: 7.115030
Stress: 111.701658 +/- 2.050142 dpmo: 0.000026, z: 4.047692
fsAlign: 0.496433 +/- 0.052797 dpmo: 0.000000, z: 5.749648
Mass: 7.415266 +/- 0.139784 dpmo: 0.000014, z: 4.183134
[ 79.44148445  51.97777164   5.78531924 509.30901632]
Frequency: 48.905550 +/- 0.856560 dpmo: 0.000000, z: 7.115030
Stress: 111.701658 +/- 2.050142 dpmo: 0.000026, z: 4.047692
fsAlign: 0.496433 +/- 0.052797 dpmo: 0.000000, z: 5.749648
Mass: 7.415266 +/- 0.139784 dpmo: 0.000014, z: 4.183134
[ 79.44148447  51.97777164   5.78531924 509.30901632]
Frequency: 48.905551 +/- 0.856560 dpmo: 0.000000, z: 7.115030
Stress: 111.701658 +/- 2.050142 dpmo: 0.000026, z: 4.047692
fsAlign: 0.496433 +/- 0.052797 dpmo: 0.000000, z: 5.749648
Mass: 7.415266 +/- 0.139784 dpmo: 0.000014, z: 4.183134
[ 79.44148445  51.97777166   5.78531924 509.30901632]
Frequency: 48.905551 +/- 0.856560 dpmo: 0.000000, z: 7.115030
Stress: 111.701658 +/- 2.050142 dpmo: 0.000026, z: 4.047692
fsAli

Frequency: 50.609321 +/- 0.895613 dpmo: 0.000000, z: 4.902432
Stress: 110.441816 +/- 2.029386 dpmo: 0.000001, z: 4.709890
fsAlign: 0.458533 +/- 0.053247 dpmo: 0.000000, z: 6.412908
Mass: 7.320260 +/- 0.141954 dpmo: 0.000001, z: 4.788455
[ 83.74409937  51.57879507   5.59531004 507.35503134]
Frequency: 50.609321 +/- 0.895613 dpmo: 0.000000, z: 4.902432
Stress: 110.441816 +/- 2.029386 dpmo: 0.000001, z: 4.709890
fsAlign: 0.458533 +/- 0.053247 dpmo: 0.000000, z: 6.412908
Mass: 7.320260 +/- 0.141954 dpmo: 0.000001, z: 4.788455
[ 83.74409937  51.57879505   5.59531005 507.35503134]
Frequency: 50.609321 +/- 0.895613 dpmo: 0.000000, z: 4.902432
Stress: 110.441816 +/- 2.029386 dpmo: 0.000001, z: 4.709890
fsAlign: 0.458533 +/- 0.053247 dpmo: 0.000000, z: 6.412908
Mass: 7.320260 +/- 0.141954 dpmo: 0.000001, z: 4.788454
[ 83.74409937  51.57879505   5.59531004 507.35503136]
Frequency: 50.609321 +/- 0.895613 dpmo: 0.000000, z: 4.902432
Stress: 110.441816 +/- 2.029386 dpmo: 0.000001, z: 4.709890
fsAli

In [31]:
print overallSystemDict

{'detectorDict': {'pos': < detectorPos = -0.5+/-0.0333 >}, 'materialDict': {'elasticModulus': < E = 200000000000.0+/-6670000000.0 >, 'density': < rho = 8.8e-06+/-0 >}, 'sourceDict': {'force': 9401.5944+/-57.46280148823399, 'beamDistToCL': < sourceR = 600.0+/-0.0667 >, 'omega': < omega = 12.56+/-0.041867 >, 'pos': -0.957828163332943+/-0.04156021552581398}, 'geometryDict': {'beamHeight': < h = 83.86556848931774+/-0.25 >, 'beamWidth': < w = 51.5672007810666+/-0.25 >, 'beamThick': < t = 5.587421904549895+/-0.1 >, 'beamLength': < L = 507.29993503195686+/-0.2 >}, 'tubeDict': {'gravity': < g = 9.81+/-0 >, 'tubeMass': < tubeMass = 90.0+/-0.08333 >, 'tubePos': < tubePos = 0.0+/-0.0333 >}, 'fsAlign': 0.45782816333294296+/-0.05325543647884327, 'xRayDict': {'fsAlign': < fsAlign = 0.0+/-0 >}, 'beamDict': {'beamFrequency': 50.64187740793825+/-0.8963773100984894, 'beamMass': 7.313840139326671+/-0.14200485094578857, 'beamDeflection': 0.957828163332943+/-0.024866875850257302, 'beamStress': 110.44884992

In [32]:
def prettyPrint_VarianceParticipation(targetUfloat):
    targetUfloat_sigma = targetUfloat.std_dev
    targetUfloat_var = targetUfloat_sigma * targetUfloat_sigma
    print_df = pd.DataFrame()
    tag_list = []
    percent_list = []
    for (var, error) in targetUfloat.error_components().items():
        percent_var = error * error/targetUfloat_var * 100
        #print "{}: {}%".format(var.tag, percent_var)
        tag_list.append(var.tag)
        percent_list.append(percent_var)
    print_df['Tag'] = tag_list
    print_df['PercentContrib'] = percent_list
    print_df.sort_values(by=['PercentContrib'], ascending=False, inplace=True)
    #print print_df
    return print_df

In [33]:
prettyPrint_VarianceParticipation(overallSystemDict['fsAlign'])

Tag  PercentContrib
5       tubePos       39.098543
6   detectorPos       39.098543
7             E       13.417982
2             t        7.278344
10        omega        0.534978
3             h        0.433861
1             w        0.103877
9             L        0.021155
4      tubeMass        0.012569
0       sourceR        0.000149
8             g        0.000000

In [34]:
prettyPrint_VarianceParticipation(overallSystemDict['beamDict']['beamStress'])

Tag  PercentContrib
2         t       68.193776
1         E       23.644929
6     omega        5.186074
3         h        1.648611
5         w        1.178701
4  tubeMass        0.121840
7         L        0.024628
0   sourceR        0.001442
8         g        0.000000

In [59]:
t_nom = (overallSystemDict['geometryDict']['beamThick']).nominal_value
t_std_orig = 0.1
overallSystemDict['geometryDict']['beamThick'] = ufloat(t_nom, 1.0*t_std_orig, 't')
overallSystemDict = forwardCalculate(fitted_params, overallSystemDict)
calculateDPMO(overallSystemDict)
#prettyPrint_VarianceParticipation(overallSystemDict['beamDict']['beamStress'])

[ 83.82874003  51.57065593   5.58939768 507.31666656]
Frequency: 50.629441 +/- 0.896085 dpmo: 0.000001, z: 4.877392
Stress: 110.453744 +/- 2.029579 dpmo: 0.000001, z: 4.703564
fsAlign: 0.458102 +/- 0.053252 dpmo: 0.000000, z: 6.420365
Mass: 7.315199 +/- 0.141988 dpmo: 0.000001, z: 4.822956


6.307711887809653e-07