In [20]:
# Import the Modules into the Notebook
from uncertainties import ufloat
from uncertainties import wrap
from uncertainties.umath import * 
import numpy as np

In [21]:
# Setup the Structure

# Geometry
geometryDict = {}
geometryDict['beamHeight'] = ufloat(100, 0.25)
geometryDict['beamLength'] = ufloat(500, 0.2)
geometryDict['beamThick'] = ufloat(4.5, 0.1)
geometryDict['beamWidth'] = ufloat(50, 0.25)
print geometryDict

materialDict = {}
materialDict['elasticModulus'] = ufloat(200E9, 6.67E9)
materialDict['density'] = ufloat(8.8E-6, 0)
print materialDict

tubeDict = {}
tubeDict['tubePos'] = ufloat(0, 0)
tubeDict['tubeMass'] = ufloat(90, 0.08333)
tubeDict['gravity'] = ufloat(9.81, 0)
print tubeDict

beamDict = {}
beamDict['beamDeflection'] = ufloat(0, 0)
beamDict['beamFrequency'] = ufloat(0, 0)
beamDict['beamStress'] = ufloat(0, 0)
beamDict['beamMass'] = ufloat(0, 0)
print beamDict

sourceDict = {}
sourceDict['pos'] = ufloat(0, 0)
sourceDict['beamDistToCL'] = ufloat(600, 0.0667)
sourceDict['omega'] = ufloat(12.56, 0.041867)
sourceDict['force'] = ufloat(0, 0)
print sourceDict

detectorDict = {}
detectorDict['pos'] = ufloat(-0.5, 0.0333)
print detectorDict

xRayDict = {}
xRayDict['fsAlign'] = ufloat(0, 0)
print xRayDict

{'beamHeight': 100.0+/-0.25, 'beamWidth': 50.0+/-0.25, 'beamThick': 4.5+/-0.1, 'beamLength': 500.0+/-0.2}
{'elasticModulus': 200000000000.0+/-6670000000.0, 'density': 8.8e-06+/-0}
{'gravity': 9.81+/-0, 'tubeMass': 90.0+/-0.08333, 'tubePos': 0.0+/-0}
{'beamFrequency': 0.0+/-0, 'beamMass': 0.0+/-0, 'beamDeflection': 0.0+/-0, 'beamStress': 0.0+/-0}
{'force': 0.0+/-0, 'beamDistToCL': 600.0+/-0.0667, 'omega': 12.56+/-0.041867, 'pos': 0.0+/-0}
{'pos': -0.5+/-0.0333}
{'fsAlign': 0.0+/-0}


In [22]:
# To permit calling and transferring information across all subsystems
# Package it into an overall dict so that the
# Analytical and Response Surface can be programmed inside the functional blocks
overallSystemDict = {}
overallSystemDict['xRayDict'] = xRayDict
overallSystemDict['detectorDict'] = detectorDict
overallSystemDict['sourceDict'] = sourceDict
overallSystemDict['beamDict'] = beamDict
overallSystemDict['tubeDict'] = tubeDict
overallSystemDict['materialDict'] = materialDict
overallSystemDict['geometryDict'] = geometryDict
print overallSystemDict


{'detectorDict': {'pos': -0.5+/-0.0333}, 'materialDict': {'elasticModulus': 200000000000.0+/-6670000000.0, 'density': 8.8e-06+/-0}, 'sourceDict': {'force': 0.0+/-0, 'beamDistToCL': 600.0+/-0.0667, 'omega': 12.56+/-0.041867, 'pos': 0.0+/-0}, 'geometryDict': {'beamHeight': 100.0+/-0.25, 'beamWidth': 50.0+/-0.25, 'beamThick': 4.5+/-0.1, 'beamLength': 500.0+/-0.2}, 'tubeDict': {'gravity': 9.81+/-0, 'tubeMass': 90.0+/-0.08333, 'tubePos': 0.0+/-0}, 'xRayDict': {'fsAlign': 0.0+/-0}, 'beamDict': {'beamFrequency': 0.0+/-0, 'beamMass': 0.0+/-0, 'beamDeflection': 0.0+/-0, 'beamStress': 0.0+/-0}}


In [23]:
# Define Analytical Equations
def defineAnalyticalEquations_Lower(overallSystemDict):
    # Equation 1
    L = overallSystemDict['geometryDict']['beamLength']
    w = overallSystemDict['geometryDict']['beamWidth']
    t = overallSystemDict['geometryDict']['beamThick']
    h = overallSystemDict['geometryDict']['beamHeight']
    density = overallSystemDict['materialDict']['density']
    # User Enters Formula
    beamMass = density * L * (2 * (w + 2 * t)*t + 2 * h * t)
    
    # Equation 2
    tubeMass = overallSystemDict['tubeDict']['tubeMass']
    beamDistToCL = overallSystemDict['sourceDict']['beamDistToCL']
    gravity = overallSystemDict['tubeDict']['gravity']
    omega =  overallSystemDict['sourceDict']['omega']
    # User Enters Formula
    force = tubeMass * (0.001 * beamDistToCL * omega * omega + gravity)
    

    # Pushed back into the Dict
    overallSystemDict['beamDict']['beamMass'] = beamMass
    overallSystemDict['sourceDict']['force'] = force
    
    return overallSystemDict

In [24]:
# 'h', 'w', 't', 'L', 'E', 'F', 
# 'h^2', 'h w', 'h t', 'h L', 'h E', 'h F', 
# 'w^2', 'w t', 'w L', 'w E', 'w F', 
# 't^2', 't L', 't E', 't F', 
# 'L^2', 'L E', 'L F', 
# 'E^2', 'E F', 
# 'F^2'
def calculateResponseValue(h, w, t, L, E, F, coef, intercept):
    term1 = h*coef[0] + w*coef[1] + t*coef[2] + L*coef[3] + E*coef[4] + F*coef[5]
    term2 = h * (h*coef[6] + w*coef[7] + t*coef[8] + L*coef[9] + E*coef[10] + F*coef[11])
    term3 = w * (w*coef[12] + t*coef[13] + L*coef[14] + E*coef[15] + F*coef[16])

    term4 = t * (t*coef[17] + L*coef[18] + E*coef[19] + F*coef[20])
    term5 = L * (L*coef[21] + E*coef[22] + F*coef[23])
    term6 = E * (E*coef[24] + F*coef[25])
    term7 = F * F * coef[26]
    return intercept + term1 + term2 + term3 + term4 + term5 + term6 + term7
    

In [25]:
def calculateCodedValues(h, w, t, L, E, F):
    # 6 Variables: h, w, t, L, E, F
    lb = np.array([80, 40, 2, 400, 180E9, 9000])
    ub = np.array([120, 60, 7, 600, 220E9, 11000])
    avg = 0.5 * (lb + ub)

    loc_array = np.array([h, w, t, L, E, F])
    loc_array_coded = (loc_array - avg) / (ub - lb) * 2.0
    #print loc_array, loc_array_coded
    return list(loc_array_coded)
    
# Define Response Surface Equations
def defineResponseSurface(overallSystemDict, freq_rs, deflection_rs, stress_rs):
    L = overallSystemDict['geometryDict']['beamLength']
    w = overallSystemDict['geometryDict']['beamWidth']
    t = overallSystemDict['geometryDict']['beamThick']
    h = overallSystemDict['geometryDict']['beamHeight']
    E = overallSystemDict['materialDict']['elasticModulus']
    F = overallSystemDict['sourceDict']['force']
    
    h_c, w_c, t_c, L_c, E_c, F_c = calculateCodedValues(h, w, t, L, E, F)
    
    
    #x_vars = np.array([h, w, t, L, E, F])
    #x_vars_n = np.array([h.n, w.n, t.n, L.n, E.n, F.n])
    #x_vars_2d = x_vars.reshape(-1,1).transpose()
    #print x_vars_2d.shape
    # beamDeflection
    beamDeflection = calculateResponseValue(h, w, t, L, E, F, deflection_rs.steps[1][1].coef_[0,1:], deflection_rs.steps[1][1].intercept_[0])
    #beamDeflection = wrap(deflection_rs.predict)(x_vars_2d)
    #loc_I = (w * h * h * h/12)
    #beamDeflection = (1.0/(E * loc_I)) * F * L * L * L
    
    # beamFrequency
    beamFrequency = calculateResponseValue(h, w, t, L, E, F, freq_rs.steps[1][1].coef_[0,1:], freq_rs.steps[1][1].intercept_[0])
    #beamFrequency = wrap(freq_rs.predict)(x_vars_2d)
    #beamFrequency = E * w * h * h * h/12
    
    # beamStress
    beamStress = calculateResponseValue(h, w, t, L, E, F, stress_rs.steps[1][1].coef_[0,1:], stress_rs.steps[1][1].intercept_[0])
    #beamStress = wrap(stress_rs.predict)(x_vars_2d)
    #beamStress = F/(w * t)
    
    
    beamDict['beamDeflection'] = beamDeflection
    beamDict['beamFrequency'] = beamFrequency
    beamDict['beamStress'] = beamStress
    return overallSystemDict

In [26]:
# Define Analytical Equations
# Has some dependency on the Response Surface Equations.. So split it into two parts (Lower and Upper)
def defineAnalyticalEquations_Upper(overallSystemDict):
    # Equation 3
    tubePos = overallSystemDict['tubeDict']['tubePos']
    beamDeflection = overallSystemDict['beamDict']['beamDeflection']
    # User Enters Formula
    sourcePos = tubePos - beamDeflection
    
    # Equation 4
    detectorPos = overallSystemDict['detectorDict']['pos']
    # User Enters Formula
    fsAlign = detectorPos - sourcePos
    
    # Pushed back into the Dict
    overallSystemDict['sourceDict']['pos'] = sourcePos
    overallSystemDict['fsAlign'] = fsAlign
    return overallSystemDict
    

In [27]:
# Test out a simple calculation
from sklearn.externals import joblib

# Load the response surfaces
# https://stackoverflow.com/questions/34373606/scikit-learn-coefficients-polynomialfeatures
freq_rs = joblib.load('freq_rs.pkl')
print freq_rs.steps[1][1].coef_.shape
print freq_rs.steps[1][1].intercept_

deflection_rs = joblib.load('deflection_rs.pkl')
stress_rs = joblib.load('stress_rs.pkl')

overallSystemDict = defineAnalyticalEquations_Lower(overallSystemDict)
overallSystemDict = defineResponseSurface(overallSystemDict, freq_rs, deflection_rs, stress_rs)
overallSystemDict = defineAnalyticalEquations_Upper(overallSystemDict)
print overallSystemDict

(1, 28)
[27.50748961]
{'detectorDict': {'pos': -0.5+/-0.0333}, 'materialDict': {'elasticModulus': 200000000000.0+/-6670000000.0, 'density': 8.8e-06+/-0}, 'sourceDict': {'force': 9401.5944+/-57.46280148823399, 'beamDistToCL': 600.0+/-0.0667, 'omega': 12.56+/-0.041867, 'pos': -0.8701628007248919+/-0.02722088446317654}, 'geometryDict': {'beamHeight': 100.0+/-0.25, 'beamWidth': 50.0+/-0.25, 'beamThick': 4.5+/-0.1, 'beamLength': 500.0+/-0.2}, 'tubeDict': {'gravity': 9.81+/-0, 'tubeMass': 90.0+/-0.08333, 'tubePos': 0.0+/-0}, 'fsAlign': 0.37016280072489194+/-0.04301007499362918, 'xRayDict': {'fsAlign': 0.0+/-0}, 'beamDict': {'beamFrequency': 54.71261517436952+/-0.9967051363964022, 'beamMass': 6.2964+/-0.14852282230173783, 'beamDeflection': 0.8701628007248919+/-0.02722088446317654, 'beamStress': 112.07475227086393+/-2.0564129698467237}}


In [28]:
import scipy.stats as st

# Define DPMO and perform the optimization on variables
# Calculate the dpmo given the ufloat object and the lsl & usl
def dpo_lsl_usl(in_ufloat, lsl, usl):
    loc_mean = in_ufloat.nominal_value
    loc_std = in_ufloat.std_dev
    ret_dpo = 0.0

    if(~np.isnan(lsl)):
        z_lsl = (loc_mean - lsl) * 1.0/loc_std
        loc_lslcdf = st.norm.cdf(z_lsl)
        ret_dpo += 1 - loc_lslcdf
    
    if(~np.isnan(usl)):
        z_usl = (usl - loc_mean) * 1.0/loc_std
        loc_uslcdf = st.norm.cdf(z_usl)
        ret_dpo += 1.0 - loc_uslcdf

    return ret_dpo

In [31]:
import scipy.optimize as optimize

# params: h, w, L, t
def f(params, overallSystemDict=overallSystemDict):
    print(params)  # <-- you'll see that params is a NumPy array
    h_nom, w_nom, t_nom, L_nom = params # <-- for readability you may wish to assign names to the component variables
    # Set the values into the Overall System Dict
    L_std = (overallSystemDict['geometryDict']['beamLength']).std_dev
    w_std = (overallSystemDict['geometryDict']['beamWidth']).std_dev
    t_std = (overallSystemDict['geometryDict']['beamThick']).std_dev
    h_std = (overallSystemDict['geometryDict']['beamHeight']).std_dev
    
    overallSystemDict['geometryDict']['beamLength'] = ufloat(L_nom, L_std) 
    overallSystemDict['geometryDict']['beamWidth'] = ufloat(w_nom, w_std)
    overallSystemDict['geometryDict']['beamThick'] = ufloat(t_nom, t_std)
    overallSystemDict['geometryDict']['beamHeight'] = ufloat(h_nom, h_std)
    
    
    overallSystemDict = defineAnalyticalEquations_Lower(overallSystemDict)
    overallSystemDict = defineResponseSurface(overallSystemDict, freq_rs, deflection_rs, stress_rs)
    overallSystemDict = defineAnalyticalEquations_Upper(overallSystemDict)

    # Calculate the DPO of each variable
    beamFrequency = overallSystemDict['beamDict']['beamFrequency']
    beamStress = overallSystemDict['beamDict']['beamStress']
    beamMass = overallSystemDict['beamDict']['beamMass']
    fsAlign = overallSystemDict['fsAlign']
    
    # print beamFrequency, beamStress, beamMass, fsAlign
    
    dpo_beamFrequency = dpo_lsl_usl(beamFrequency, np.nan, 55.0)
    #bounds_beamFrequency = (np.nan, 55)
    dpo_beamStress = dpo_lsl_usl(beamStress, np.nan, 120)
    #bounds_beamStress = (np.nan, 20)
    dpo_beamMass = dpo_lsl_usl(beamMass, np.nan, 8.0)
    #bounds_beamMass = (np.nan, 8)
    dpo_fsAlign = dpo_lsl_usl(fsAlign, -0.8, 0.8)
    #bounds_fsAlign = (0.4, 0.6)
    dpo_avg = 0.25 * (dpo_beamFrequency + dpo_beamStress + dpo_beamMass + dpo_fsAlign)

    print 'Frequency: %f, dpmo: %f'%(beamFrequency.nominal_value, dpo_beamFrequency)
    print 'Stress: %f, dpmo: %f'%(beamStress.nominal_value, dpo_beamStress)
    print 'fsAlign: %f, dpmo: %f'%(fsAlign.nominal_value, dpo_fsAlign)
    print 'Mass: %f, dpmo: %f'%(beamMass.nominal_value, dpo_beamMass)
    
    
    return dpo_avg

h_Nom_init = 100 #(overallSystemDict['geometryDict']['beamHeight']).nominal_value
w_Nom_init = 50 #(overallSystemDict['geometryDict']['beamWidth']).nominal_value
t_Nom_init = 4.5 #(overallSystemDict['geometryDict']['beamThick']).nominal_value
L_Nom_init = 500 #(overallSystemDict['geometryDict']['beamLength']).nominal_value

initial_guess = [h_Nom_init, w_Nom_init, t_Nom_init, L_Nom_init]
bounds = np.c_[[80, 40, 2, 400], [120, 60, 7, 600]]
result = optimize.minimize(f, initial_guess, method='BFGS', bounds=bounds, options={'gtol': 1e-6, 'disp': True})
if result.success:
    fitted_params = result.x
    print(fitted_params)
else:
    raise ValueError(result.message)

[100.   50.    4.5 500. ]
Frequency: 54.712615, dpmo: 0.386545
Stress: 112.074752, dpmo: 0.000058
fsAlign: 0.370163, dpmo: 0.000000
Mass: 6.296400, dpmo: 0.000000
[100.00000001  50.           4.5        500.        ]
Frequency: 54.712615, dpmo: 0.386545
Stress: 112.074752, dpmo: 0.000058
fsAlign: 0.370163, dpmo: 0.000000
Mass: 6.296400, dpmo: 0.000000
[100.          50.00000001   4.5        500.        ]
Frequency: 54.712615, dpmo: 0.386545
Stress: 112.074752, dpmo: 0.000058
fsAlign: 0.370163, dpmo: 0.000000
Mass: 6.296400, dpmo: 0.000000
[100.          50.           4.50000001 500.        ]
Frequency: 54.712615, dpmo: 0.386545
Stress: 112.074752, dpmo: 0.000058
fsAlign: 0.370163, dpmo: 0.000000
Mass: 6.296400, dpmo: 0.000000
[100.          50.           4.5        500.00000001]
Frequency: 54.712615, dpmo: 0.386545
Stress: 112.074752, dpmo: 0.000058
fsAlign: 0.370163, dpmo: 0.000000
Mass: 6.296400, dpmo: 0.000000
[100.   50.    4.5 500. ]
Frequency: 54.712615, dpmo: 0.386545
Stress: 11

Frequency: 53.168844, dpmo: 0.027927
Stress: 116.115748, dpmo: 0.033966
fsAlign: 0.406314, dpmo: 0.000000
Mass: 5.956387, dpmo: 0.000000
[ 99.75716358  50.00931124   4.2744991  500.10549027]
Frequency: 53.168844, dpmo: 0.027927
Stress: 116.115748, dpmo: 0.033966
fsAlign: 0.406314, dpmo: 0.000000
Mass: 5.956387, dpmo: 0.000000
[ 99.75716358  50.00931122   4.27449912 500.10549027]
Frequency: 53.168844, dpmo: 0.027927
Stress: 116.115748, dpmo: 0.033966
fsAlign: 0.406314, dpmo: 0.000000
Mass: 5.956387, dpmo: 0.000000
[ 99.75716358  50.00931122   4.2744991  500.10549028]
Frequency: 53.168844, dpmo: 0.027927
Stress: 116.115748, dpmo: 0.033966
fsAlign: 0.406314, dpmo: 0.000000
Mass: 5.956387, dpmo: 0.000000
[ 99.54314168  50.02974916   4.2854044  500.20236042]
Frequency: 53.093216, dpmo: 0.023017
Stress: 116.153477, dpmo: 0.035370
fsAlign: 0.407985, dpmo: 0.000000
Mass: 5.966259, dpmo: 0.000000
[ 99.54314168  50.02974916   4.2854044  500.20236042]
Frequency: 53.093216, dpmo: 0.023017
Stress: 

Frequency: 50.086337, dpmo: 0.000000
Stress: 113.293975, dpmo: 0.000623
fsAlign: 0.471704, dpmo: 0.000000
Mass: 6.993378, dpmo: 0.000000
[ 85.5347729   51.38597182   5.31623835 506.54869577]
Frequency: 50.086337, dpmo: 0.000000
Stress: 113.293974, dpmo: 0.000623
fsAlign: 0.471704, dpmo: 0.000000
Mass: 6.993378, dpmo: 0.000000
[ 85.5347729   51.38597182   5.31623833 506.54869579]
Frequency: 50.086337, dpmo: 0.000000
Stress: 113.293975, dpmo: 0.000623
fsAlign: 0.471704, dpmo: 0.000000
Mass: 6.993378, dpmo: 0.000000
[ 83.69680346  51.56411804   5.45496633 507.381432  ]
Frequency: 49.713133, dpmo: 0.000000
Stress: 112.860346, dpmo: 0.000281
fsAlign: 0.479563, dpmo: 0.000000
Mass: 7.120330, dpmo: 0.000000
[ 83.69680346  51.56411804   5.45496633 507.381432  ]
Frequency: 49.713133, dpmo: 0.000000
Stress: 112.860346, dpmo: 0.000281
fsAlign: 0.479563, dpmo: 0.000000
Mass: 7.120330, dpmo: 0.000000
[ 83.69680347  51.56411804   5.45496633 507.381432  ]
Frequency: 49.713133, dpmo: 0.000000
Stress: 

fsAlign: 0.497786, dpmo: 0.000000
Mass: 7.404679, dpmo: 0.000010
[ 79.4185683   51.97885503   5.77838103 509.31977218]
Frequency: 48.847493, dpmo: 0.000000
Stress: 111.842584, dpmo: 0.000035
fsAlign: 0.497786, dpmo: 0.000000
Mass: 7.404679, dpmo: 0.000010
[ 79.41856828  51.97885504   5.77838103 509.31977218]
Frequency: 48.847493, dpmo: 0.000000
Stress: 111.842584, dpmo: 0.000035
fsAlign: 0.497786, dpmo: 0.000000
Mass: 7.404679, dpmo: 0.000010
[ 79.41856828  51.97885503   5.77838104 509.31977218]
Frequency: 48.847493, dpmo: 0.000000
Stress: 111.842584, dpmo: 0.000035
fsAlign: 0.497786, dpmo: 0.000000
Mass: 7.404679, dpmo: 0.000010
[ 79.41856828  51.97885503   5.77838103 509.3197722 ]
Frequency: 48.847493, dpmo: 0.000000
Stress: 111.842584, dpmo: 0.000035
fsAlign: 0.497786, dpmo: 0.000000
Mass: 7.404679, dpmo: 0.000010
[ 79.37390642  51.98333561   5.78288568 509.33996842]
Frequency: 48.845408, dpmo: 0.000000
Stress: 111.812908, dpmo: 0.000033
fsAlign: 0.497813, dpmo: 0.000000
Mass: 7.409

Frequency: 50.733932, dpmo: 0.000001
Stress: 110.201093, dpmo: 0.000001
fsAlign: 0.455668, dpmo: 0.000000
Mass: 7.334336, dpmo: 0.000001
[ 83.87129077  51.56861148   5.60174597 507.2968878 ]
Frequency: 50.733932, dpmo: 0.000001
Stress: 110.201092, dpmo: 0.000001
fsAlign: 0.455668, dpmo: 0.000000
Mass: 7.334336, dpmo: 0.000001
[ 83.87129077  51.56861148   5.60174596 507.29688782]
Frequency: 50.733932, dpmo: 0.000001
Stress: 110.201093, dpmo: 0.000001
fsAlign: 0.455668, dpmo: 0.000000
Mass: 7.334336, dpmo: 0.000001
[ 83.66461777  51.58768523   5.61018485 507.3907716 ]
Frequency: 50.647854, dpmo: 0.000001
Stress: 110.273224, dpmo: 0.000001
fsAlign: 0.457588, dpmo: 0.000000
Mass: 7.338191, dpmo: 0.000002
[ 83.66461777  51.58768523   5.61018485 507.3907716 ]
Frequency: 50.647854, dpmo: 0.000001
Stress: 110.273224, dpmo: 0.000001
fsAlign: 0.457588, dpmo: 0.000000
Mass: 7.338191, dpmo: 0.000002
[ 83.66461778  51.58768523   5.61018485 507.3907716 ]
Frequency: 50.647854, dpmo: 0.000001
Stress: 